---
detect:
  title: appcmd_pid_0001_list_config
  description:
    - List service account credentials from app pools on a server
  detectType: single_line_match
  detectLanguage: kql
  detectCon: 2
  urgency: high
  inTheWild: unknown
  noiseProjection: low
  regressionVolume: only attack pattern match
  analysisEffort: normal
  confidence: high
intel:
  tags:
    -
  attackId:
    - t1003
  references:
    - ref_appcmd.md
  emulation:
    - art_t1003_test5_uid_42510244-5019-48fa-a0e5-66c3b76e6049
  pattern:
    -
dataRequirements:
  dataSource:
    - windows_os
  dataType:
    - process_creation
  dataCollector: m365d_agent
  dataForwardTo: m365d_security_center
  dataParser:
  dataStorage: m365d_security_center
  dataTable: device_process_events
  dataIndex:
  dataAccess: api_advanced_hunting
  dataMap:
logic:
  kqlVar:
  kqlTable: DeviceProcessEvents
  kqlQuery: | 
    | where ProcessCommandLine has_all ('list', 'apppool', 'config')
      and ProcessCommandLine contains @'/config'