import socpuppet.detectpy.windows_os.cmstp
import socpuppet.detectpy.windows_os.comsvcs
import socpuppet.detectpy.windows_os.control
import socpuppet.detectpy.windows_os.keymgr
import socpuppet.detectpy.windows_os.mimikatz
import socpuppet.detectpy.windows_os.msdt
import socpuppet.detectpy.windows_os.mshta
import socpuppet.detectpy.windows_os.nltest
import socpuppet.detectpy.windows_os.net
import socpuppet.detectpy.windows_os.procdump
import socpuppet.detectpy.windows_os.pypykatz
import socpuppet.detectpy.windows_os.reg