---
title: entraid_p0001_federation_trust_settings_modified
metaTags:
  description: user or app modifies federation settings in the tenant
  detectUseCase:
  detectType: single_line_match
  detectCon: 2
  tags:
intel:
  attackTechnique: t1484.002
  attackSoftware:
  references:
    - https://docs.microsoft.com/office365/troubleshoot/active-directory/update-federated-domain-office-365
    - https://docs.microsoft.com/openspecs/windows_protocols/ms-adfspp/e7b9ea73-1980-4318-96a6-da559486664b
    - https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/whatis-fed
    - https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-fed-whatis
    - https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-monitor-federation-changes
    - https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Microsoft%20Entra%20ID/Analytic%20Rules/ADFSDomainTrustMods.yaml
    - https://docs.datadoghq.com/security/default_rules/m365-modification-of-federated-domain/
  emulation:
  pattern:
dataRequirements:
  dataScope: entra_id
  dataCollector: azure_active_directory
  dataName:
  dataForwardTo: msft_sentinel
  dataAccess: azure_monitor_api
  dataStorage: audit_logs
  dataMap: audit_logs
kqlDetect:
  kqlVar:
  kqlTable: AuditLogs
  kqlQuery: |
    | where OperationName =~ "Set federation settings on domain"
      or OperationName =~ "Set domain authentication"