---
detect:
  title: registryt1003_pid_0002_security
  description:
    - Powershell Used to Export Security HIVE
  detectType: single_line_match
  detectLanguage: kql
  detectCon: 2
  urgency:
  inTheWild:
  noiseProjection:
  regressionVolume:
  analysisEffort:
  confidence:
intel:
  tags:
    -
  attackId:
    - t1003
  references:
    -
  emulation:
    -
  pattern:
    -
dataRequirements:
  dataSource:
    - windows_os
  dataType:
    - process_creation
  dataCollector: m365d_agent
  dataForwardTo: m365d_security_center
  dataParser:
  dataStorage: m365d_security_center
  dataTable: device_process_events
  dataIndex:
  dataAccess: api_advanced_hunting
  dataMap:
logic:
  kqlVar:
  kqlTable: DeviceProcessEvents
  kqlQuery: | 
    | where ProcessCommandLine has_any (@'HKLM\security ', @'HKEY_LOCAL_MACHINE\security ')
    | where ProcessCommandLine has_all ('Get', 'Property', 'Out', 'File')
      or ProcessCommandLine has_all ('Export', 'CliXml')