---
title: appcmd_pid_0001_list_config
intel:
  description:
    - List service account credentials from app pools on a server
  detectType: single_line_match
  detectCon: 1
  detectLanguage: kql
  tags:
    - lol
  attackTechnique:
    - t1003
  attackSoftware:
  references:
  emulation:
    - atomic_red_team_t1003_001_t5_guid_42510244-5019-48fa-a0e5-66c3b76e6049
  pattern:
dataRequirements:
  dataSource: windows_os
  dataType: process_create
  dataCollector: m365d_agent
  dataForwardTo: m365d_security_center
  dataParser:
  dataStorage: m365d_security_center
  dataTable: device_process_events
  dataIndex:
  dataAccess: api_advanced_hunting
  dataMap:
logic:
  kqlVar:
  kqlTable: DeviceProcessEvents
  kqlQuery: |
    | where FileName =~ 'appcmd.exe'
      and ProcessCommandLine contains 'list'
      and ProcessCommandLine contains 'apppool'
    | where ProcessCommandLine contains @'/config'
