from socpuppet.detectpy_deprecate.windows_os.control.control import *
from socpuppet.detectpy_deprecate.windows_os.esentutl.esentutul import *
from socpuppet.detectpy_deprecate.windows_os.hh.hh import *
from socpuppet.detectpy_deprecate.windows_os.infdefaultinstall.infdefaultinstall import *
from socpuppet.detectpy_deprecate.windows_os.keymgr.keymgr import *
from socpuppet.detectpy_deprecate.windows_os.mavinject.mavinject import *
from socpuppet.detectpy_deprecate.windows_os.mimikatz.mimikatz import *
from socpuppet.detectpy_deprecate.windows_os.msdt.msdt import *
from socpuppet.detectpy_deprecate.windows_os.mshta.mshta import *
from socpuppet.detectpy_deprecate.windows_os.net.net import *
from socpuppet.detectpy_deprecate.windows_os.netsh.netsh import *
from socpuppet.detectpy_deprecate.windows_os.procdump.procdump import *
from socpuppet.detectpy_deprecate.windows_os.pypykatz.pypykatzz import *
from socpuppet.detectpy_deprecate.windows_os.reg.reg import *
from socpuppet.detectpy_deprecate.windows_os.wuauclt.wuauclt import *