---
title: rolemgt_pid_0001_any_global_admin
intel:
  description:
    - user or app modifies federation settings in the tenant
  detectType: single_line_match
  detectCon: 3
  detectLanguage: kql
  tags:
    -
  attackTechnique:
    - t1098.003
  attackSoftware:
  references:
  emulation:
  pattern:
dataRequirements:
  dataSource: entra_id
  dataType:
    - core_directory
  dataCollector: azure_active_directory
  dataForwardTo: msft_sentinel
  dataParser:
  dataStorage: azure_monitor
  dataTable: audit_logs
  dataIndex: directory_management
  dataAccess: api_azure_monitor
  dataMap:
logic:
  kqlVar:
  kqlTable: AuditLogs
  kqlQuery: |
    | where OperationName =~ "Set federation settings on domain"
      or OperationName =~ "Set domain authentication"